/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Actividad4_4;

import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author pablo
 */
public class Ejercicio2 extends javax.swing.JFrame {

    private int tipoSorteo = -1;
    private ArrayList<Equipo> listaEquipos = new ArrayList<>();
    JFrame ventanaError = new JFrame();
    /**
     * Creates new form Ejercicio2
     */
    public Ejercicio2() {
        initComponents();
        botonRegistrar.setEnabled(false);
        botonEmparejar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ventanaRegistrar = new javax.swing.JDialog();
        title1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        botonTerminar = new javax.swing.JButton();
        botonAñadirEquipo = new javax.swing.JButton();
        campoNombre = new javax.swing.JTextField();
        campoPais = new javax.swing.JTextField();
        grupoComboBox = new javax.swing.JComboBox<>();
        posicion1 = new javax.swing.JCheckBox();
        posicion2 = new javax.swing.JCheckBox();
        ventanaSorteo = new javax.swing.JDialog();
        title2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        sorteoComboBox = new javax.swing.JComboBox<>();
        aceptarSorteo = new javax.swing.JButton();
        ventanaEmparejar = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        textAreaEmparejamientos = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        botonRegistrar = new javax.swing.JButton();
        botonTipoSorteo = new javax.swing.JButton();
        botonEmparejar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaListaEquipos = new javax.swing.JTextArea();

        ventanaRegistrar.setSize(new java.awt.Dimension(400, 400));

        title1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        title1.setText("Registar equipos");

        jLabel2.setText("Nombre");

        jLabel3.setText("País");

        jLabel4.setText("Grupo");

        jLabel5.setText("Posición");

        botonTerminar.setText("Terminar");
        botonTerminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTerminarActionPerformed(evt);
            }
        });

        botonAñadirEquipo.setText("Añadir equipo");
        botonAñadirEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAñadirEquipoActionPerformed(evt);
            }
        });

        grupoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D", "E", "F", "G", "H" }));
        grupoComboBox.setSelectedIndex(-1);

        posicion1.setText("1");
        posicion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posicion1ActionPerformed(evt);
            }
        });

        posicion2.setText("2");
        posicion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posicion2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ventanaRegistrarLayout = new javax.swing.GroupLayout(ventanaRegistrar.getContentPane());
        ventanaRegistrar.getContentPane().setLayout(ventanaRegistrarLayout);
        ventanaRegistrarLayout.setHorizontalGroup(
            ventanaRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ventanaRegistrarLayout.createSequentialGroup()
                .addContainerGap(93, Short.MAX_VALUE)
                .addComponent(title1)
                .addGap(112, 112, 112))
            .addGroup(ventanaRegistrarLayout.createSequentialGroup()
                .addGroup(ventanaRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ventanaRegistrarLayout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addGroup(ventanaRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(ventanaRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ventanaRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(campoPais, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(grupoComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(ventanaRegistrarLayout.createSequentialGroup()
                                .addComponent(posicion1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(posicion2))))
                    .addGroup(ventanaRegistrarLayout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(botonTerminar))
                    .addGroup(ventanaRegistrarLayout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(botonAñadirEquipo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ventanaRegistrarLayout.setVerticalGroup(
            ventanaRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventanaRegistrarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title1)
                .addGap(18, 18, 18)
                .addGroup(ventanaRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ventanaRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(campoPais, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ventanaRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(grupoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ventanaRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(posicion1)
                    .addComponent(posicion2))
                .addGap(16, 16, 16)
                .addComponent(botonAñadirEquipo)
                .addGap(18, 18, 18)
                .addComponent(botonTerminar)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        ventanaSorteo.setSize(new java.awt.Dimension(400, 300));

        title2.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        title2.setText("Tipo de sorteo");

        jLabel1.setText("Selecciona el sorteo a realizar");

        sorteoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Octavos de final", "Cuartos de final", "Semifinales" }));
        sorteoComboBox.setSelectedIndex(-1);

        aceptarSorteo.setText("Aceptar");
        aceptarSorteo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarSorteoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ventanaSorteoLayout = new javax.swing.GroupLayout(ventanaSorteo.getContentPane());
        ventanaSorteo.getContentPane().setLayout(ventanaSorteoLayout);
        ventanaSorteoLayout.setHorizontalGroup(
            ventanaSorteoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventanaSorteoLayout.createSequentialGroup()
                .addContainerGap(122, Short.MAX_VALUE)
                .addGroup(ventanaSorteoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ventanaSorteoLayout.createSequentialGroup()
                        .addGroup(ventanaSorteoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(title2))
                        .addGap(105, 105, 105))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ventanaSorteoLayout.createSequentialGroup()
                        .addComponent(sorteoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(128, 128, 128))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ventanaSorteoLayout.createSequentialGroup()
                        .addComponent(aceptarSorteo)
                        .addGap(155, 155, 155))))
        );
        ventanaSorteoLayout.setVerticalGroup(
            ventanaSorteoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventanaSorteoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title2)
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(sorteoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(aceptarSorteo)
                .addContainerGap(112, Short.MAX_VALUE))
        );

        ventanaEmparejar.setSize(new java.awt.Dimension(600, 300));

        textAreaEmparejamientos.setEditable(false);
        textAreaEmparejamientos.setColumns(20);
        textAreaEmparejamientos.setRows(5);
        jScrollPane2.setViewportView(textAreaEmparejamientos);

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel6.setText("Enfrentamientos");

        jLabel7.setIcon(new javax.swing.ImageIcon("/Users/pablo/Downloads/sorteo.gif")); // NOI18N

        javax.swing.GroupLayout ventanaEmparejarLayout = new javax.swing.GroupLayout(ventanaEmparejar.getContentPane());
        ventanaEmparejar.getContentPane().setLayout(ventanaEmparejarLayout);
        ventanaEmparejarLayout.setHorizontalGroup(
            ventanaEmparejarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventanaEmparejarLayout.createSequentialGroup()
                .addGroup(ventanaEmparejarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ventanaEmparejarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ventanaEmparejarLayout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(jLabel6)))
                .addContainerGap(128, Short.MAX_VALUE))
        );
        ventanaEmparejarLayout.setVerticalGroup(
            ventanaEmparejarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ventanaEmparejarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ventanaEmparejarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(100, 100, 100))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        title.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        title.setText("Sorteo UEFA");

        botonRegistrar.setText("Registrar equipos");
        botonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarActionPerformed(evt);
            }
        });

        botonTipoSorteo.setText("Tipo de sorteo");
        botonTipoSorteo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTipoSorteoActionPerformed(evt);
            }
        });

        botonEmparejar.setText("Emparejar");
        botonEmparejar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEmparejarActionPerformed(evt);
            }
        });

        textAreaListaEquipos.setEditable(false);
        textAreaListaEquipos.setColumns(20);
        textAreaListaEquipos.setRows(5);
        jScrollPane1.setViewportView(textAreaListaEquipos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(129, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(title)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonTipoSorteo)
                            .addComponent(botonRegistrar)
                            .addComponent(botonEmparejar))))
                .addGap(123, 123, 123))
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title)
                .addGap(29, 29, 29)
                .addComponent(botonRegistrar)
                .addGap(18, 18, 18)
                .addComponent(botonTipoSorteo)
                .addGap(18, 18, 18)
                .addComponent(botonEmparejar)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonTipoSorteoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTipoSorteoActionPerformed
        // TODO add your handling code here:
        ventanaSorteo.setVisible(true);
    }//GEN-LAST:event_botonTipoSorteoActionPerformed

    private void aceptarSorteoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarSorteoActionPerformed
        // TODO add your handling code here:
        tipoSorteo = sorteoComboBox.getSelectedIndex(); //0 = Octavos; 1 = Cuartos; 2 = Semifinales
        ventanaSorteo.setVisible(false);
        
        if (tipoSorteo != -1){
            botonRegistrar.setEnabled(true);
        }
    }//GEN-LAST:event_aceptarSorteoActionPerformed

    private void posicion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posicion2ActionPerformed
        // TODO add your handling code here:
        if (posicion1.isSelected()){
            posicion1.setSelected(false);
        }
    }//GEN-LAST:event_posicion2ActionPerformed

    private void botonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarActionPerformed
        // TODO add your handling code here:
        ventanaRegistrar.setVisible(true);
        
        if (tipoSorteo != 0){
            grupoComboBox.setEnabled(false);
            posicion1.setEnabled(false);
            posicion2.setEnabled(false);
        }
    }//GEN-LAST:event_botonRegistrarActionPerformed

    private void botonAñadirEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAñadirEquipoActionPerformed
        // TODO add your handling code here:
        if (tipoSorteo != 0 && !campoNombre.getText().equals("") && !campoPais.getText().equals("")){
            listaEquipos.add(new Equipo(campoNombre.getText(), campoPais.getText()));
            
            if (tipoSorteo == 1 && listaEquipos.size() == 8){
                botonAñadirEquipo.setEnabled(false);
            }
            else if (tipoSorteo == 2 && listaEquipos.size() == 4){
                botonAñadirEquipo.setEnabled(false);
            }
        }
        else if (!campoNombre.getText().equals("") && !campoPais.getText().equals("") && grupoComboBox.getSelectedIndex()!= -1){
            if (posicion1.isSelected()){
                listaEquipos.add(new Equipo(campoNombre.getText(), campoPais.getText(), grupoComboBox.getSelectedItem().toString(), 1));
            }
            else if (posicion2.isSelected()){
                listaEquipos.add(new Equipo(campoNombre.getText(), campoPais.getText(), grupoComboBox.getSelectedItem().toString(), 2));
            }
            
            if (listaEquipos.size() == 16){
                botonAñadirEquipo.setEnabled(false);
            }
        }
        campoNombre.setText("");
        campoPais.setText("");
    }//GEN-LAST:event_botonAñadirEquipoActionPerformed

    private void botonTerminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTerminarActionPerformed
        // TODO add your handling code here:
        int equiposRestantes = 0;
        String mensaje;
        
        if (tipoSorteo == 0 && listaEquipos.size() != 16){
            equiposRestantes = 16 - listaEquipos.size();
            mensaje = "Te faltan por añadir " + equiposRestantes + " equipos.";
            JOptionPane.showMessageDialog(ventanaError, mensaje);
        }
        else if (tipoSorteo == 1 && listaEquipos.size() != 8){
            equiposRestantes = 8 - listaEquipos.size();
            mensaje = "Te faltan por añadir " + equiposRestantes + " equipos.";
            JOptionPane.showMessageDialog(ventanaError, mensaje);
        }
        else if (tipoSorteo == 2 && listaEquipos.size() != 4){
            equiposRestantes = 4 - listaEquipos.size();
            mensaje = "Te faltan por añadir " + equiposRestantes + " equipos.";
            JOptionPane.showMessageDialog(ventanaError, mensaje);
        }
        else{
            ventanaRegistrar.setVisible(false);
            textAreaListaEquipos.append("EQUIPOS" + "\n");
            
            for (int i=0; i < listaEquipos.size(); i++){
                textAreaListaEquipos.append(i+1 + "." + listaEquipos.get(i).getNombre() + "\n");
            }
            
            botonRegistrar.setEnabled(false);
            botonTipoSorteo.setEnabled(false);
            botonEmparejar.setEnabled(true);
        }
    }//GEN-LAST:event_botonTerminarActionPerformed

    private void posicion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posicion1ActionPerformed
        // TODO add your handling code here:
        if (posicion2.isSelected()){
            posicion2.setSelected(false);
        }
    }//GEN-LAST:event_posicion1ActionPerformed

    private void botonEmparejarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEmparejarActionPerformed
        // TODO add your handling code here:
        ventanaEmparejar.setVisible(true);
        int numEmparejamientos = listaEquipos.size()/2;
        Equipo equipo1 = null;
        Equipo equipo2 = null;
        int numRandom = 0;
        boolean unicoPais = true;
        
        for (int x=0; x < listaEquipos.size() && unicoPais; x++){
            if (listaEquipos.get(x).getPais() != listaEquipos.get(x+1).getPais()){
                unicoPais = false;
            }
        }
        
        for (int i=0; i < numEmparejamientos; i++){
            numRandom = (int) (Math.random()*listaEquipos.size());
            equipo1 = listaEquipos.get(numRandom);
            listaEquipos.remove(numRandom);

            if (tipoSorteo == 0){
                do{
                    numRandom = (int) (Math.random()*listaEquipos.size());
                    equipo2 = listaEquipos.get(numRandom);
                } while (equipo1.getGrupo().equals(equipo2.getGrupo()) || equipo1.getPosicion() == equipo2.getPosicion() || equipo1.getPais().equals(equipo2.getPais()));
            }
            else{
                if (unicoPais){
                    numRandom = (int) (Math.random()*listaEquipos.size());
                    equipo2 = listaEquipos.get(numRandom);
                }
                else{
                    do{
                        numRandom = (int) (Math.random()*listaEquipos.size());
                        equipo2 = listaEquipos.get(numRandom);
                    } while (equipo1.getPais().equals(equipo2.getPais()));
                }
                
            }
            listaEquipos.remove(numRandom);

            textAreaEmparejamientos.append(i+1 + ". " + equipo1.getNombre() + " - "  + equipo2.getNombre() + "\n");
        }
        
    }//GEN-LAST:event_botonEmparejarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicio2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptarSorteo;
    private javax.swing.JButton botonAñadirEquipo;
    private javax.swing.JButton botonEmparejar;
    private javax.swing.JButton botonRegistrar;
    private javax.swing.JButton botonTerminar;
    private javax.swing.JButton botonTipoSorteo;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JTextField campoPais;
    private javax.swing.JComboBox<String> grupoComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JCheckBox posicion1;
    private javax.swing.JCheckBox posicion2;
    private javax.swing.JComboBox<String> sorteoComboBox;
    private javax.swing.JTextArea textAreaEmparejamientos;
    private javax.swing.JTextArea textAreaListaEquipos;
    private javax.swing.JLabel title;
    private javax.swing.JLabel title1;
    private javax.swing.JLabel title2;
    private javax.swing.JDialog ventanaEmparejar;
    private javax.swing.JDialog ventanaRegistrar;
    private javax.swing.JDialog ventanaSorteo;
    // End of variables declaration//GEN-END:variables
}
