/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ejercicio1;

import java.awt.*;
import javax.swing.*;

/**
 *
 * @author pablo
 */
public class tableroAjedrez extends javax.swing.JFrame {

    private JButton boton[] = new JButton[64];
    /**
     * Creates new form tableroAjedrez
     */
    public tableroAjedrez() {
        initComponents();
        
        this.setLayout(new GridLayout(8, 8));
        
        for(int i = 0; i < 64; i++){
            boton[i] = new JButton(Integer.toString(i));
            
            //Controlamos las filas cuya primera casilla es negra
            if(i < 8 || i > 15 && i < 24 || i > 31 && i < 40 || i > 47 && i < 56){
                //En estas filas las casillas pares son de color negro y las impares blancas
                if(i % 2 == 0){
                    boton[i].setBackground(Color.black);
                    boton[i].setForeground(Color.white);
                }else{
                    boton[i].setBackground(Color.white);
                    boton[i].setForeground(Color.black);
                }
            }
            //El resto de filas se colorean de manera inversa
            else{
                if(i % 2 == 0){
                    boton[i].setBackground(Color.white);
                    boton[i].setForeground(Color.black);
                }else{
                    boton[i].setBackground(Color.black);
                    boton[i].setForeground(Color.white);
                }
            }
        }
        
        //Añadimos los botones al layout
        for(int j = 0; j < 64; j++){
            this.add(boton[j]);
        }
        
        this.setTitle("Tablero ajedrez");
        this.setVisible(true);
        this.pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tableroAjedrez.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tableroAjedrez.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tableroAjedrez.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tableroAjedrez.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tableroAjedrez().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
